development: &default
  clients:
    default:
      username: <%= ENV['MONGO_USER'] %>
      password: <%= ENV['MONGO_PASS'] %>
      database: amqp_development_mongo
      hosts:
        - localhost:27017

production:
  clients:
    default:
      username: <%= ENV['MONGO_USER'] %>
      password: <%= ENV['MONGO_PASS'] %>
      database: amqp_production_mongo
      hosts:
        - localhost:27017

test:
  clients:
    default:
      username: <%= ENV['MONGO_USER'] %>
      password: <%= ENV['MONGO_PASS'] %>
      database: amqp_test_mongo
      hosts:
        - localhost:27017
